In [35]:
# !pip install pandas

Requirement already satisfied: pandas in /home/vce/.local/lib/python3.8/site-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/vce/.local/lib/python3.8/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/vce/.local/lib/python3.8/site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.1 in /home/vce/.local/lib/python3.8/site-packages (from pandas) (2024.1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /home/vce/.local/lib/python3.8/site-packages (from pandas) (1.24.3)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas) (1.14.0)

In [36]:
import pandas as pd
import numpy as np
b = pd.Series([1,2,3,4,5])
b, type(b)

(0    1
 1    2
 2    3
 3    4
 4    5
 dtype: int64,
 pandas.core.series.Series)

In [37]:
b.sum(), b.min(), b.max(), b.mean(), b.median(), b.count(), b.prod(), b.var(), b[1:3]

(15,
 1,
 5,
 3.0,
 3.0,
 5,
 120,
 2.5,
 1    2
 2    3
 dtype: int64)

In [38]:
data = pd.Series([1, np.nan, 'hello', None])
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [39]:
data.isnull(), data.notnull(), data.fillna(25), data.dropna()

(0    False
 1     True
 2    False
 3     True
 dtype: bool,
 0     True
 1    False
 2     True
 3    False
 dtype: bool,
 0        1
 1       25
 2    hello
 3       25
 dtype: object,
 0        1
 2    hello
 dtype: object)

In [40]:
import numpy as np
x = pd.Series([1, "hello", 'a', "Ramesh", np.nan])
x, x.isnull(), x.notnull(), x.fillna(25), x.dropna()

(0         1
 1     hello
 2         a
 3    Ramesh
 4       NaN
 dtype: object,
 0    False
 1    False
 2    False
 3    False
 4     True
 dtype: bool,
 0     True
 1     True
 2     True
 3     True
 4    False
 dtype: bool,
 0         1
 1     hello
 2         a
 3    Ramesh
 4        25
 dtype: object,
 0         1
 1     hello
 2         a
 3    Ramesh
 dtype: object)

In [41]:
population_dict = {'California': 38332521, 'Texas': 26448193, 'New York': 19651127,
'Florida': 19552860, 'Illinois': 12882135}
population = pd.Series(population_dict)
print(population)
print(population.shape)
print("======================================")
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
print(area)
print(area.shape)

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64
(5,)
======================================
California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64
(5,)

In [42]:
states = pd.DataFrame({'population': population, 'area': area})
states

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [43]:
states["No.of.College"] = [np.nan, None, 200, 100, pd.NA]
states

            population    area No.of.College
California    38332521  423967           NaN
Texas         26448193  695662          None
New York      19651127  141297           200
Florida       19552860  170312           100
Illinois      12882135  149995          <NA>

In [44]:
states.isnull(), states.notnull(), states.fillna(0), states.dropna()

(            population   area  No.of.College
 California       False  False           True
 Texas            False  False           True
 New York         False  False          False
 Florida          False  False          False
 Illinois         False  False           True,
             population  area  No.of.College
 California        True  True          False
 Texas             True  True          False
 New York          True  True           True
 Florida           True  True           True
 Illinois          True  True          False,
             population    area  No.of.College
 California    38332521  423967              0
 Texas         26448193  695662              0
 New York      19651127  141297            200
 Florida       19552860  170312            100
 Illinois      12882135  149995              0,
           population    area No.of.College
 New York    19651127  141297           200
 Florida     19552860  170312           100)

In [45]:
import pandas as pd

data = pd.read_csv("employees.csv")
data

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,08-06-1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,03-04-2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,11/23/2014,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [46]:
import pandas as pd
pd.notnull(data["Gender"]), pd.isnull(data["Gender"])

(0       True
 1       True
 2       True
 3       True
 4       True
        ...
 995    False
 996     True
 997     True
 998     True
 999     True
 Name: Gender, Length: 1000, dtype: bool,
 0      False
 1      False
 2      False
 3      False
 4      False
        ...
 995     True
 996    False
 997    False
 998    False
 999    False
 Name: Gender, Length: 1000, dtype: bool)

In [47]:
data.fillna({"Gender": "No Gender"}, inplace = True)
data

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,08-06-1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,03-04-2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,No Gender,11/23/2014,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales